version: "3.5"
services:
  webserver:
    image: fuerzastudio/nginx-php-fpm:version-.1.0.2
    container_name: server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php/php.ini:/etc/php/7.4/fpm/php.ini
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/common:/etc/nginx/common
      - ./nginx/htpasswd:/etc/nginx/htpasswd # user-project | 1gZSxWt2etUNTG6QKV6n
      - ./cache:/var/cache/nginx/fastcgi_temp/cache
      - /var/www:/var/www
    networks: 
      dev:
        ipv4_address: 171.28.5.10
  server-database:
    image: mariadb:10.5.9
    container_name: mariadb
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passroot
      - MYSQL_USER=example_usr              
      - MYSQL_PASSWORD=example_pass
      - MYSQL_DATABASE=example_db               
    ports:
      - '3306:3306'
    networks: 
      dev:
        ipv4_address: 171.28.5.11

networks: 
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 171.28.0.0/16